### ISSUE TITLE
Add a switch option to the gates

### ISSUE THREAD

**Issue by hectorsector** [github/learning-lab-components#139]
## Feature Request

**Describe the problem/friction you are trying to solve**
I am unable to learners through different paths int he course from their selected preferences. 

**Describe your ideal solution**
I'd like the option to have a switch statement of sorts. Something like this:
```yaml
- type: switch
  case:
    - type: respond [ ... ] 
   case: 
    - type: createPullRequest [...]
```

**Describe alternatives you have considered**
In order to get this kind of behavior, I currently have to repeat logic in multiple gates (that are actually inverted) [example](https://github.com/githubtraining/continuous-delivery/pull/23/commits/90dfd09c83598d792ab914d26f981e21f876d97b)
