### ISSUE TITLE
Add 'labels' option to createIssue

### ISSUE THREAD

**Issue by mattdavis0351** [github/learning-lab-components#141]
## Feature Request

**Describe the problem/friction you are trying to solve**
Currently when using the `createIssue` action there is no way to add labels to the issue at the time of creation

**Describe your ideal solution**
```yaml
type: createIssue
title: Title of the issue
body: issue-body.md
labels:
  - bug
  - feature
  - some other label
```

**Describe alternatives you have considered**
- Use octokit to create the issue
- Have the user add the label, less than ideal when creating courses around workflows that do stuff based on the labels an issue has.
