### ISSUE TITLE
updateBranchProtection not working

### ISSUE THREAD

**Issue by mattdavis0351** [github/learning-lab-components#147]
## Bug Report

**Current behavior**
In the `before:` step updating branch protection works as expected

```yaml
before:
  - type: updateBranchProtection
```

Later in the course re-enabling it fails and prevents the step from running, which prevented the `createIssue` action from running and the course was unrecoverable.

```yaml
    event: pull_request.closed
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: updateBranchProtection
      - type: createIssue
```

**Reproduction**
Steps to reproduce the behavior in GitHub Learning Lab:
1. Enroll in `GitHub Actions: Using GitHub Script`
1. Follow course until you need to merge first PR
1. After merging PR you will not get a response

To test bug
1. Comment out the `updateBranchProtection` step
1. Enroll in `GitHub Actions: Using GitHub Script`
1. Follow course until you need to merge first PR
1. After merging PR you will a new issue is created

**Expected behavior**
A clear and concise description of what you expected to happen (with optional code snippets).

Branch protection for master would be re-enabled after user megerd
